version: '3.3'
services:
  nginx:
    image: valistarguo/nginx-proxy-manager:latest
    deploy:
      replicas: 1
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: jc21/mariadb-aria:latest
    deploy:
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: nginx
      MYSQL_DATABASE: nginx
      MYSQL_USER: nginx
      MYSQL_PASSWORD: nginx
    volumes:
      - nginx_mysql:/var/lib/mysql
volumes:
  nginx_data:
  nginx_letsencrypt:
  nginx_mysql:
